## medical_appointment_api/settings.py
import os
from dotenv import load_dotenv
from pathlib import Path

"""
Django settings for medical_appointment_api project.

Generated by 'django-admin startproject' using Django 5.0.0.
"""

# Carrega as variáveis de ambiente do arquivo .env
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Use a variável de ambiente carregada
SECRET_KEY = os.environ.get('SECRET_KEY')

# Use a variável de ambiente carregada para DEBUG (e converte para booleano)
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 't')

# Use a variável de ambiente carregada para ALLOWED_HOSTS
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework', # Adicionado para construir a API
    
    # Local apps
    'professionals', # Seu primeiro app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medical_appointment_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medical_appointment_api.wsgi.application'


# Database
# Por padrão, vamos manter o SQLite 3. Depois, configuraremos o PostgreSQL (psycopg2)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        
        # Lê variáveis de ambiente do docker-compose.yml ou usa fallback (padrão)
        'NAME': os.environ.get('POSTGRES_NAME', 'medical_appointment_db'),
        'USER': os.environ.get('POSTGRES_USER', 'docker_user'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'docker_password'),
        
        # O hostname 'db' é o nome do serviço definido no docker-compose.yml
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization

LANGUAGE_CODE = 'pt-br' # Alterado para Português do Brasil

TIME_ZONE = 'America/Sao_Paulo' # Alterado para o fuso horário de São Paulo

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'